### ISSUE TITLE
Can not run or debug anything from hover_actions

### ISSUE THREAD

**Issue by ovidiu-ionescu** [simrat39/rust-tools.nvim#285]
If I start hover_actions with the cursor over a test, the menu shows up with two options 
![image](https://user-images.githubusercontent.com/1642705/204163988-a5bd2ceb-57f6-4cc3-845c-b0f063dc4e19.png)
but I can not move the selection with the keyboard. If I press enter with the Run entry active, the popup just closes.

`:RustRunnables` allows me to run the test.

Also, if I use the mouse to activate Debug, it seems to start and the cursor moves to the first breakpoint.

**Comment by Gremious** [comment]
Your cursor does not look like it's inside the action window. Re-run `:RustHoverActions` while it's already on screen, and it should "focus" it.

By default, the first call to e.g. `:RustHoverActions` will only create a window, while a second call will move you into it (since most the time you want to just glance at the e.g. type info)

Yhis can be toggled to be default behavior with `hover_actions.focus` (see config)

**Comment by ovidiu-ionescu** [comment]
That was indeed the case, thanks for the answer,
