### ISSUE TITLE
The folder 'images' have 54.46 MB

### ISSUE THREAD

**Issue by Rodrigodd** [simrat39/rust-tools.nvim#3]
When I use vim-plug, it download that folder, which I think is unnecessary. Maybe you could host this images in some other site, like imgur?

**Comment by simrat39** [comment]
https://github.com/simrat39/rust-tools.nvim/commit/96a2575617cd144847b9c71dbc6520939a24d96c handles this. I did not realize that the gif's would take that much space, although the damage has been done, it will help reduce the size later on. Thanks for the report :+1:

**Comment by simrat39** [comment]
Actually, looks like vim-plug shallow clones, so if anyone wants to get rid of the large size, remove it from your plug conifg, source the file, do a :PlugClean, add it back, do a :PlugInstall and the size should be reduced

**Comment by resolritter** [comment]
IMO now that Github supports embedding videos, they should be preferred over GIFs since they allow for slowing down, pausing, re-watching from a certain point, etc.

You could remove the gifs from the Git history using something like [git-filter-repo](https://github.com/newren/git-filter-repo#bfg-repo-cleaner), then they'll be gone for good.

btw @simrat39 which UI is used for the gifs?

**Comment by simrat39** [comment]
> IMO now that Github supports embedding videos, they should be preferred over GIFs since they allow for slowing down, pausing, re-watching from a certain point, etc.
> 
> You could remove the gifs from the Git history using something like [git-filter-repo](https://github.com/newren/git-filter-repo#bfg-repo-cleaner), then they'll be gone for good.
> 
> btw @simrat39 which UI is used for the gifs?

Yup will have to rerecord videos, git-filter-repo sound cool, ill use it to remove the gifs from the git history

neovide is the gui btw
https://github.com/Kethku/neovide

Thanks for the tips :+1:
