### ISSUE TITLE
Convert to manual impl puts `$0` in front of generated fn

### ISSUE THREAD

**Issue by lowstar** [simrat39/rust-tools.nvim#60]
Hello,

Convert to manual impl puts `$0` in front of generated `fn`. 

```rust
#[derive(Debug, Clone)]
pub struct Foo {
    pub value: u32,
}
```

After calling "Convert to manual ..." code action, I get this:

```rust
pub struct Foo {
    pub value: u32,
}

impl std::fmt::Debug for Foo {
    $0fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("Foo").field("value", &self.value).finish()
    }
}

impl Clone for Foo {
    $0fn clone(&self) -> Self {
        Self { value: self.value.clone() }
    }
}
```

That `$0` in front of `fn` seems strange and I don't know where it came from.

**Comment by simrat39** [comment]
This happens because of this https://github.com/rust-analyzer/rust-analyzer/blob/master/docs/dev/lsp-extensions.md#snippet-textedit. And i initally enabled this feature because without it we weren't getting the proper Convert to manual... code action working. I'll revert it for now because it seems to be leaking into other things, but i'll open an issue on rust analyzer regarding the Convert to manual... code action without snippet text edit

**Comment by simrat39** [comment]
Ok this is properly fixed now
